version : '3.5'

networks:
  trscdnc:
    driver: bridge

services:
  nest-db:
    container_name: postgres
    image: postgres:14-alpine3.15
    networks:
      - trscdnc
    env_file:
      - ../.env
    restart: on-failure

  nestjs:
    container_name: nestjs
    image: nestjs
    ports:
      - "5555:5555"
      - "3333:3333"
    env_file:
      - ../.env
    depends_on:
      - nest-db
    build:
      context: nestjs_app/
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - trscdnc


  reactjs:
    container_name: reactjs
    image: reactjs
    depends_on:
      - nestjs
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    build:
      context: front/
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - trscdnc

  # nginx:
  #   container_name: nginx
  #   image: nginx
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - reactjs
  #   build:
  #     context: nginx/
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   networks:
  #     - trscdnc
#    volumes:
#      - nginx_config:/etc/nginx/
#      - nginx_logs:/var/log/nginx
#
#volumes:
#  nginx_config:
#  nginx_logs: